from vector.Vector import Vector

A = [8, 3, 2, 9, 12, 4, 7,3,9,8,8]
v = Vector(capacity=None, size=5, v=1, A=A)
v.sort()
print(v.getlist())
v.uniquify()
print(v.getlist())
print(v.size())
num = v.find(8)
print(num)
print(v[1])
v[1] = 6
print(v[1])
v.insert(9)
print(v[7])
v.insert(8, 0)
print(v[0])
print(v.getlist())
v.remove(0)
print(v.getlist())
print(v.size())
v.remove(1, 3)
print(v.getlist())
print(v.size())
print(v.find(1,0,1))
v.insert(4,2)
v.insert(6)
print(v.getlist())
v.deduplicate()
print(v.getlist())
print(v.size())
def fun1(a):
    return a*2
v.traverse(fun1)
print(v.getlist())
